{{- $fullName := printf "%s" (include "azurite.fullname" . ) -}}
{{- if .Values.config.blobs.initJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    {{- include "azurite.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
    spec:
      {{- with .Values.config.blobs.initJob.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: azurite-init-containers
          image: "{{ .Values.config.blobs.initJob.image.repository}}:{{ .Values.config.blobs.initJob.image.version | toString }}"
          env:
            env:
              {{- range $key, $value := .Values.config.blobs.initJob.env }}
              - name: {{ $key }}
                value: "{{ $value }}"
              {{- end }}
      restartPolicy: OnFailure
  backoffLimit: 10
{{- end }}