on:
  push:
    branches:
      - 'main'
      - 'beeqube'
    paths:
      - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - run: |
          cp -f README.md ${{ runner.temp }}/README.md
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
